[package]
name = "icarus"
version = "2.0.0"
edition = "2021"
description = "ICARUS: fast flexible protein structural alignment based on Protein Units"
license = "CECILL-2.1"
readme = "README.md"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
flate2 = "1"
rayon = "1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false

[profile.profiling]
inherits = "release"
debug = true
